CREATE TABLE IF NOT EXISTS STOCK_QUERY_RECORD (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    SYMBOL        VARCHAR(100),
    PRICE         FLOAT(24),
    PRICE_CHANGE  FLOAT(24),
    CHANGE_PERCENT FLOAT(24),
    VOLUME        BIGINT,
    DAY_HIGH      FLOAT(24),
    DAY_LOW       FLOAT(24),
    CURRENCY      VARCHAR(20),
    QUERIED_AT    TIMESTAMP
);
