CREATE TABLE IF NOT EXISTS STOCK_QUERY_RECORD (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    SYMBOL        VARCHAR(100),
    PRICE         FLOAT(24),
    PRICE_CHANGE  FLOAT(24),
    CHANGE_PERCENT FLOAT(24),
    VOLUME        BIGINT,
    DAY_HIGH      FLOAT(24),
    DAY_LOW       FLOAT(24),
    CURRENCY      VARCHAR(20),
    QUERIED_AT    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STOCK_NEWS_RECORD (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    SYMBOL        VARCHAR(100),
    TITLE         VARCHAR(1024),
    LINK          VARCHAR(8192),
    PUBLISHER     VARCHAR(1024),
    PUBLISHED_AT  VARCHAR(1024)
);